import type { ShipmentDraft } from "./types";
import { mergeWithSample } from "./sample-data";

export function mapStateToShipmentPayload(state: ShipmentDraft) {
  return {
    document_batch: state.documentBatch,
    si_number: state.siNumber,
    bl_number: state.blNumber,
    invoice_number: state.invoiceNumber,
    issue_date: state.issueDate || null,
    etd: state.etd || null,
    eta: state.eta || null,
    shipped_on_board: state.shippedOnBoard || null,
    stuffing_date: state.stuffingDate || null,
    booking_number: state.bookingNumber,
    freight_term: state.freightTerm,
    trade_term: state.tradeTerm,
    place_of_loading: state.placeOfLoading,
    port_of_loading: state.portOfLoading,
    port_of_discharge: state.portOfDischarge,
    final_destination: state.finalDestination,
    vessel: state.vessel,
    voyage: state.voyage,
    connecting_vessel: state.connectingVessel,
    detention_note: state.detentionNote,
    shipper: state.shipper,
    consignee: state.consignee,
    notify_party: state.notifyParty,
    carrier: state.carrier,
    attention: state.attention,
    bill_to: state.billTo,
    payment_note: state.paymentNote,
    bank_name: state.bankName,
    bank_account_number: state.bankAccountNumber,
    bank_account_name: state.bankAccountName,
    signer_name: state.signerName,
    signer_title: state.signerTitle,
  };
}

export function mapShipmentToState(
  shipment: Record<string, string | null>,
  containers: Record<string, string | null>[],
  cargoItems: Record<string, string | null>[],
  invoiceItems: Record<string, string | number | null>[],
): ShipmentDraft {
  return mergeWithSample({
    id: shipment.id ?? null,
    documentBatch: shipment.document_batch ?? "",
    siNumber: shipment.si_number ?? "",
    blNumber: shipment.bl_number ?? "",
    invoiceNumber: shipment.invoice_number ?? "",
    issueDate: shipment.issue_date ?? "",
    etd: shipment.etd ?? "",
    eta: shipment.eta ?? "",
    shippedOnBoard: shipment.shipped_on_board ?? "",
    stuffingDate: shipment.stuffing_date ?? "",
    bookingNumber: shipment.booking_number ?? "",
    freightTerm: shipment.freight_term ?? "",
    tradeTerm: shipment.trade_term ?? "",
    placeOfLoading: shipment.place_of_loading ?? "",
    portOfLoading: shipment.port_of_loading ?? "",
    portOfDischarge: shipment.port_of_discharge ?? "",
    finalDestination: shipment.final_destination ?? "",
    vessel: shipment.vessel ?? "",
    voyage: shipment.voyage ?? "",
    connectingVessel: shipment.connecting_vessel ?? "",
    detentionNote: shipment.detention_note ?? "",
    shipper: shipment.shipper ?? "",
    consignee: shipment.consignee ?? "",
    notifyParty: shipment.notify_party ?? "",
    carrier: shipment.carrier ?? "",
    attention: shipment.attention ?? "",
    billTo: shipment.bill_to ?? "",
    paymentNote: shipment.payment_note ?? "",
    bankName: shipment.bank_name ?? "",
    bankAccountNumber: shipment.bank_account_number ?? "",
    bankAccountName: shipment.bank_account_name ?? "",
    signerName: shipment.signer_name ?? "",
    signerTitle: shipment.signer_title ?? "",
    containers: containers.map((row) => ({
      id: row.id ?? null,
      containerNumber: row.container_number ?? "",
      sealNumber: row.seal_number ?? "",
      type: row.container_type ?? "",
      grossWeight: row.gross_weight ?? "",
      netWeight: row.net_weight ?? "",
      measurement: row.measurement ?? "",
    })),
    cargo: cargoItems.map((row) => ({
      id: row.id ?? null,
      marks: row.marks ?? "",
      description: row.description ?? "",
      packages: row.packages ?? "",
      grossWeight: row.gross_weight ?? "",
      netWeight: row.net_weight ?? "",
      measurement: row.measurement ?? "",
    })),
    invoiceItems: invoiceItems.map((row) => ({
      id: typeof row.id === "string" ? row.id : null,
      description: typeof row.description === "string" ? row.description : "",
      quantity: String(row.quantity ?? 0),
      unit: typeof row.unit === "string" ? row.unit : "",
      unitPrice: String(row.unit_price ?? 0),
    })),
  });
}
